[pytest]
# TEST 파일을 어디에서 찾을지
testpaths = tests

# async 테스트 함수에 매번 @pytest.mark.asyncio를 붙이지 않아도 되게 한다.
# asyncio_mode를 auto로 설정한다.
# ⚠️ auto가 아니면 async 테스트가 실행되지 않고 통과한 것처럼 보인다.
asyncio_mode = auto

# 테스트용 event loop의 수명 범위
# function = 테스트 함수 하나마다 new loop를 만든다. (서로 간섭하지 않도록)
asyncio_default_fixture_loop_scope = function
